version: '3.8'

services:
  web:
    build:
      context: ./php-app
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Utipec2025*'
      MYSQL_DATABASE: estacionesp32
    volumes:
      - data_sistema_nuevo_2:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

  mcp-ai:
    build:
      context: ./mcp-server
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 'Utipec2025*'
      DB_NAME: estacionesp32
    depends_on:
      - db

  chat-web:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    ports:
      - "3000:8080"
    environment:
      - WEBUI_AUTH=True
    volumes:
      - chat_data:/app/backend/data

volumes:
  data_sistema_nuevo_2:
  chat_data: